In [41]:
from sklearn.neighbors import NearestNeighbors
import sklearn
from PDB import PDB
from Structure import superposition3d
import SymDesignUtils as SDUtils

In [17]:
%load_ext autoreload
%autoreload 2

In [18]:
!pwd

/home/kylemeador/symdesign/jupyter_notebooks


In [15]:
sklearn.show_versions()
X = [[0], [3], [1], [-0.4], [1.2]]
neigh = NearestNeighbors(algorithm='ball_tree', radius=1.5)
neigh.fit(X)

A, I = neigh.radius_neighbors(sort_results=True)
print(A)
print(I)
# A.toarray()
# A = neigh.radius_neighbors_graph(X, mode='distance', sort_results=True)
# A.toarray()


System:
    python: 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20)  [GCC 9.3.0]
executable: /home/kylemeador/miniconda3/bin/python
   machine: Linux-5.4.0-67-generic-x86_64-with-debian-bullseye-sid

Python dependencies:
          pip: 21.0.1
   setuptools: 49.6.0.post20210108
      sklearn: 0.24.1
        numpy: 1.19.5
        scipy: 1.5.3
       Cython: None
       pandas: 1.2.1
   matplotlib: 3.3.3
       joblib: 1.0.1
threadpoolctl: 2.1.0

Built with OpenMP: True
[array([0.4, 1. , 1.2]) array([], dtype=float64) array([0.2, 1. , 1.4])
 array([0.4, 1.4]) array([0.2, 1.2])]
[array([3, 2, 4]) array([], dtype=int64) array([4, 0, 3]) array([0, 2])
 array([2, 0])]


In [7]:
B = neigh.radius_neighbors_graph(mode='distance')  #, sort_results=True)
# B
B.toarray()

array([[0. , 0. , 1. , 0.4, 1.2],
       [0. , 0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 1.4, 0.2],
       [0.4, 0. , 1.4, 0. , 0. ],
       [1.2, 0. , 0.2, 0. , 0. ]])

In [19]:
test_file = '/home/kylemeador/symdesign/successful_designs/biological_assemblies/4NWN.pdb1'
files = SDUtils.get_all_file_paths('/home/kylemeador/symdesign/successful_designs/biological_assemblies/', extension='.pdb1')

In [ ]:
files = [test_file]
symmetries = ['T']

In [35]:
for file, sym in zip(files, symmetries):
    pdb = PDB.from_file(file)
    homo_pdb = PDB.from_chains(pdb.entities[0].chains, metadata=pdb)
    oriented_pdb = homo_pdb.orient(sym=sym)
    asu = pdb.return_asu(chain=pdb.entities[0].chains[0].name)
    rmsd, rot, tx, rescale = superposition3d(asu.chains[0].get_ca_coords(), oriented_pdb.chains[0].get_ca_coords())
    transformed_asu = asu.return_transformed_copy(rotation=rot, translation=tx)
    transformed_asu.write(out_path=os.path.join('/home/kylemeador/symdesign/successful_designs/asus', '%s.pdb1' % transformed_asu.name))

# Below were tests for a single design

In [36]:
print(homo_pdb.chain_id_list)
homo_pdb.name

['A', 'C', 'E', 'G', 'I', 'K', 'M', 'O', 'Q', 'S', 'U', 'W']


'4NWN'

In [38]:
oriented_pdb = homo_pdb.orient(sym='T')
# oriented_pdb.write(out_path=os.path.join('/home/kylemeador/symdesign/successful_designs/oriented/half', '%s.pdb1' % oriented_pdb.name))

In [39]:
### Need to transform the asu onto the half oriented_pdb

In [ ]:
asu = pdb.return_asu(chain=pdb.entities[0].chains[0].name)
rmsd, rot, tx, rescale = superposition3d(asu.chains[0].get_ca_coords(), oriented_pdb.chains[0].get_ca_coords())
transformed_asu = asu.return_transformed_copy(rotation=rot, translation=tx)

In [24]:
transformed_asu.write(out_path=os.path.join('/home/kylemeador/symdesign/successful_designs/asus', '%s.pdb1' % transformed_asu.name))

'/home/kylemeador/symdesign/successful_designs/asus/4NWN_PDB.pdb1'